---
title: "Modelling of R  with only Incidence data"
output: 
  github_document:
    fig_width: 10
    fig_height: 4
vignette: >
  %\VignetteIndexEntry{Modelling of R  with only Incidence data}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

This vignette describes how changes in $R_t$ can be modelled with just incidence data and discrete SI.

## Flu 1918

We use the Flu data from 1918 as an example. 
```{r Flu1918comp}
library(epidemia)
data("Flu1918")
options(mc.cores = parallel::detectCores())
print(Flu1918)
flu <- Flu1918
flu$incidence <- c(rep(NA,1),flu$incidence) ## pad before initialisation
flu$fludate <- as.Date("1918-01-01")+seq(0,along.with=flu$incidence)
obs <- !is.na(flu$incidence)

args <- list(formula=Rt(country,date)~rw(date,3),
             data=data.frame(country="A",date=flu$fludate),
             obs=list(
                 incidence=list(
                     odata=data.frame(country="A",
                                      date=flu$fludate[obs],incidence=flu$incidence[obs]),
                     rates=list(means=data.frame(factor("A"),1),
                                scale=.01),
                     pvec=c(.25,.25,.25,.25)
                 )
             ),
             seed_days=7,
             algorithm="sampling",
             r0=3,
             pops=data.frame(country="A",pop=1e6),
             si=flu$si,
             prior = rstanarm::normal(location=0,scale=.2),
             prior_intercept = rstanarm::normal(location=0,scale=.5),
             prior_tau = rstanarm::exponential(rate=4)             
             )
args$sampling_args <- list(iter=1000,control=list(adapt_delta=0.95,max_treedepth=15),seed=713)
```

```{r sampleflu, results='hide', cache=TRUE}
fit <- do.call("epim",args)
```

```{r plotflu, fig_height= 4}
library(gridExtra)
grid.arrange(plot_rt(fit),
             plot_obs(fit,"incidence"),
             nrow=2)
```

