
---
title: "Time-dependent Modelling of R"
output: 
  github_document:
    fig_width: 10
    fig_height: 4
vignette: >
  %\VignetteIndexEntry{Time-dpendent Modelling of R}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

## Data

```{r}
library(epidemia)
data("EuropeCovid")
args <- EuropeCovid
```


Add days to the covariates
```{r}
args$data$day <- as.integer(args$data$date-min(args$data$date))
```

Set sampling parameters.
```{r}
args$algorithm <- "sampling"
options(mc.cores = parallel::detectCores())
args$sampling_args <- list(iter=200,control=list(adapt_delta=0.95,max_treedepth=15))
```

### Piecewise constant

```{r}
args$group_subset <- c("United_Kingdom","Germany")
args$formula <- R(country,date) ~ 0 +  (cut(day,seq(-1,120,by=14))|country)
```

```{r,results='hide'}
fit <- do.call("epim", args)
```

```{r plotpiecewisecontantUK}
plot_rt(fit, "United_Kingdom")
plot_rt(fit, "Germany")
```



### Piecewise Linear


```{r}
library(splines)
args$formula <- R(country,date) ~ 0 + lockdown+ (bs(day,knots=seq(0,100,by=14),degree=3,intercept=TRUE)|country)
```

```{r,results='hide'}
fit <- do.call("epim", args)
```

```{r plotlinearUK}
plot_rt(fit, "United_Kingdom")
```

```{r plotlinearGermany}
plot_rt(fit, "Germany")
```

### Single Countries

```{r}
args$group_subset <- c("Germany")
args$formula <- R(country,date) ~ 0 +  bs(day,knots=seq(0,100,by=14),degree=2,intercept=TRUE)
args$formula <- R(country,date) ~ 0 +  lockdown
args$formula <- R(country,date) ~ 0 +  cut(day,seq(-1,120,by=14))
fit <- do.call("epim", args)
plot_rt(fit, "Germany")
```






